DROP TABLE IF EXISTS DrillPattern;
DROP TABLE IF EXISTS Drilling;
DROP TABLE IF EXISTS DrillHole;

DROP TABLE IF EXISTS DrillLog;
DROP TABLE IF EXISTS Drill;

DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS Quarry;
DROP TABLE IF EXISTS DrillType;

DROP TABLE IF EXISTS EmployeeRole;
