// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebApp.Entities;

public partial class Drilling
{
    public int DrillingInstanceNo { get; set; }

    public int Ssn { get; set; }

    public int MachineId { get; set; }

    public DateTime Date { get; set; }

    public decimal Duration { get; set; }

    public virtual Drill Machine { get; set; } = null!;

    public virtual Employee SsnNavigation { get; set; } = null!;
}