// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebApp.Entities;

public partial class DrillType
{
    public string ModelName { get; set; } = null!;

    public string Manufacture { get; set; } = null!;

    public virtual ICollection<Drill> Drills { get; set; } = new List<Drill>();
}