// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Entities;

public partial class DrillLogContext : DbContext
{
    public DrillLogContext(DbContextOptions<DrillLogContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Drill> Drills { get; set; }

    public virtual DbSet<DrillHole> DrillHoles { get; set; }

    public virtual DbSet<DrillLog> DrillLogs { get; set; }

    public virtual DbSet<DrillPattern> DrillPatterns { get; set; }

    public virtual DbSet<DrillType> DrillTypes { get; set; }

    public virtual DbSet<Drilling> Drillings { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<EmployeeRole> EmployeeRoles { get; set; }

    public virtual DbSet<Quarry> Quarries { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Drill>(entity =>
        {
            entity.HasKey(e => e.MachineId).HasName("PK__Drill__44EE5B58ADA1BA5E");

            entity.ToTable("Drill");

            entity.Property(e => e.MachineId)
                .ValueGeneratedNever()
                .HasColumnName("MachineID");
            entity.Property(e => e.ModelName)
                .HasMaxLength(100)
                .IsFixedLength();
            entity.Property(e => e.Rebuilts).HasDefaultValue(0);

            entity.HasOne(d => d.ModelNameNavigation).WithMany(p => p.Drills)
                .HasForeignKey(d => d.ModelName)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Drill_DrillType");
        });

        modelBuilder.Entity<DrillHole>(entity =>
        {
            entity.HasKey(e => e.HoleId).HasName("PK__DrillHol__68FB6FC16FADE579");

            entity.ToTable("DrillHole");

            entity.Property(e => e.HoleId).ValueGeneratedNever();
            entity.Property(e => e.BrokenMaterial).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.CompetentRock).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.Degrees).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.Easting).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.Elevation).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.MachineId).HasColumnName("MachineID");
            entity.Property(e => e.Northing).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.Notes)
                .HasMaxLength(500)
                .IsFixedLength();
            entity.Property(e => e.ShotId).HasColumnName("ShotID");
            entity.Property(e => e.TotalDepth).HasColumnType("decimal(18, 0)");

            entity.HasOne(d => d.Machine).WithMany(p => p.DrillHoles)
                .HasForeignKey(d => d.MachineId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DrillHole_Drill");

            entity.HasOne(d => d.Shot).WithMany(p => p.DrillHoles)
                .HasForeignKey(d => d.ShotId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DrillHole_DrillLog");
        });

        modelBuilder.Entity<DrillLog>(entity =>
        {
            entity.HasKey(e => e.ShotId).HasName("PK__DrillLog__66C5A7EF91A92A25");

            entity.ToTable("DrillLog");

            entity.Property(e => e.ShotId)
                .ValueGeneratedNever()
                .HasColumnName("ShotID");
            entity.Property(e => e.DrillerSsn).HasColumnName("DrillerSSN");
            entity.Property(e => e.QuarryName)
                .HasMaxLength(100)
                .IsFixedLength();

            entity.HasOne(d => d.DrillerSsnNavigation).WithMany(p => p.DrillLogs)
                .HasForeignKey(d => d.DrillerSsn)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DrillLog_Employee");

            entity.HasOne(d => d.QuarryNameNavigation).WithMany(p => p.DrillLogs)
                .HasForeignKey(d => d.QuarryName)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DrillLog_Quarry");
        });

        modelBuilder.Entity<DrillPattern>(entity =>
        {
            entity.HasKey(e => e.PatternId).HasName("PK__DrillPat__0A631B5211091C79");

            entity.ToTable("DrillPattern");

            entity.Property(e => e.PatternId).ValueGeneratedNever();
            entity.Property(e => e.BlasterSsn).HasColumnName("BlasterSSN");
            entity.Property(e => e.Burden).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.FaceHeight).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.HoleDiameter).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.ShotId).HasColumnName("ShotID");
            entity.Property(e => e.ShotType)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.Spacing).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.SubDrill).HasColumnType("decimal(18, 0)");

            entity.HasOne(d => d.BlasterSsnNavigation).WithMany(p => p.DrillPatterns)
                .HasForeignKey(d => d.BlasterSsn)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DrillPattern_Employee");

            entity.HasOne(d => d.Shot).WithMany(p => p.DrillPatterns)
                .HasForeignKey(d => d.ShotId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DrillPattern_DrillLog");
        });

        modelBuilder.Entity<DrillType>(entity =>
        {
            entity.HasKey(e => e.ModelName).HasName("PK__DrillTyp__67DC63B4EF4205E0");

            entity.ToTable("DrillType");

            entity.Property(e => e.ModelName)
                .HasMaxLength(100)
                .IsFixedLength();
            entity.Property(e => e.Manufacture)
                .HasMaxLength(100)
                .IsFixedLength();
        });

        modelBuilder.Entity<Drilling>(entity =>
        {
            entity.HasKey(e => e.DrillingInstanceNo).HasName("PK__Drilling__30BCF6FEF69D8990");

            entity.ToTable("Drilling");

            entity.Property(e => e.DrillingInstanceNo).ValueGeneratedNever();
            entity.Property(e => e.Duration).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.MachineId).HasColumnName("MachineID");
            entity.Property(e => e.Ssn).HasColumnName("SSN");

            entity.HasOne(d => d.Machine).WithMany(p => p.Drillings)
                .HasForeignKey(d => d.MachineId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Drilling_Drill");

            entity.HasOne(d => d.SsnNavigation).WithMany(p => p.Drillings)
                .HasForeignKey(d => d.Ssn)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Drilling_Employee");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.Ssn).HasName("PK__Employee__CA1E8E3DB901A45F");

            entity.ToTable("Employee");

            entity.Property(e => e.Ssn)
                .ValueGeneratedNever()
                .HasColumnName("SSN");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsFixedLength();
            entity.Property(e => e.FirstName)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.JobTitle)
                .HasMaxLength(100)
                .IsFixedLength();
            entity.Property(e => e.LastName)
                .HasMaxLength(100)
                .IsFixedLength();
            entity.Property(e => e.PhoneNo)
                .HasMaxLength(15)
                .IsFixedLength();
            entity.Property(e => e.SupervisorSsn).HasColumnName("SupervisorSSN");

            entity.HasOne(d => d.JobTitleNavigation).WithMany(p => p.Employees)
                .HasForeignKey(d => d.JobTitle)
                .HasConstraintName("FK_Employee_EmployeeRole");

            entity.HasOne(d => d.SupervisorSsnNavigation).WithMany(p => p.InverseSupervisorSsnNavigation)
                .HasForeignKey(d => d.SupervisorSsn)
                .HasConstraintName("FK_Employee_Employee");
        });

        modelBuilder.Entity<EmployeeRole>(entity =>
        {
            entity.HasKey(e => e.JobTitle).HasName("PK__Employee__44C68B9E44B19453");

            entity.ToTable("EmployeeRole");

            entity.Property(e => e.JobTitle)
                .HasMaxLength(100)
                .IsFixedLength();
            entity.Property(e => e.Role)
                .HasMaxLength(50)
                .IsFixedLength();
        });

        modelBuilder.Entity<Quarry>(entity =>
        {
            entity.HasKey(e => e.Name).HasName("PK__Quarry__737584F71C2DD758");

            entity.ToTable("Quarry");

            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .IsFixedLength();
            entity.Property(e => e.Company)
                .HasMaxLength(100)
                .IsFixedLength();
            entity.Property(e => e.Location)
                .HasMaxLength(250)
                .IsFixedLength();
            entity.Property(e => e.RockType)
                .HasMaxLength(200)
                .IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}