// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebApp.Entities;

public partial class DrillPattern
{
    public int PatternId { get; set; }

    public int ShotNo { get; set; }

    public decimal HoleDiameter { get; set; }

    public decimal Burden { get; set; }

    public decimal Spacing { get; set; }

    public decimal FaceHeight { get; set; }

    public decimal SubDrill { get; set; }

    public string ShotType { get; set; } = null!;

    public int NoHoles { get; set; }

    public DateTime? DesignDate { get; set; }

    public DateTime? ShotDate { get; set; }

    public int BlasterSsn { get; set; }

    public int ShotId { get; set; }

    public virtual Employee BlasterSsnNavigation { get; set; } = null!;

    public virtual DrillLog Shot { get; set; } = null!;
}