// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebApp.Entities;

public partial class DrillHole
{
    public int HoleId { get; set; }

    public int HoleNo { get; set; }

    public decimal Easting { get; set; }

    public decimal Northing { get; set; }

    public decimal Elevation { get; set; }

    public decimal Degrees { get; set; }

    public decimal BrokenMaterial { get; set; }

    public decimal? CompetentRock { get; set; }

    public decimal TotalDepth { get; set; }

    public int? WaterDepth { get; set; }

    public string? Notes { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public int MachineId { get; set; }

    public int ShotId { get; set; }

    public virtual Drill Machine { get; set; } = null!;

    public virtual DrillLog Shot { get; set; } = null!;
}