// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebApp.Entities;

public partial class Drill
{
    public int MachineId { get; set; }

    public string ModelName { get; set; } = null!;

    public int Age { get; set; }

    public int TotalHours { get; set; }

    public int? Rebuilts { get; set; }

    public virtual ICollection<DrillHole> DrillHoles { get; set; } = new List<DrillHole>();

    public virtual ICollection<Drilling> Drillings { get; set; } = new List<Drilling>();

    public virtual DrillType ModelNameNavigation { get; set; } = null!;
}