// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebApp.Entities;

public partial class DrillLog
{
    public int ShotId { get; set; }

    public DateTime TimeBegan { get; set; }

    public DateTime? TimeLastSaved { get; set; }

    public DateTime? TimeSubmitted { get; set; }

    public int DrillerSsn { get; set; }

    public string QuarryName { get; set; } = null!;

    public virtual ICollection<DrillHole> DrillHoles { get; set; } = new List<DrillHole>();

    public virtual ICollection<DrillPattern> DrillPatterns { get; set; } = new List<DrillPattern>();

    public virtual Employee DrillerSsnNavigation { get; set; } = null!;

    public virtual Quarry QuarryNameNavigation { get; set; } = null!;
}