// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebApp.Entities;

public partial class Employee
{
    public int Ssn { get; set; }

    public string? JobTitle { get; set; }

    public int? SupervisorSsn { get; set; }

    public string FirstName { get; set; } = null!;

    public string LastName { get; set; } = null!;

    public string PhoneNo { get; set; } = null!;

    public string? Email { get; set; }

    public int? LicenseNo { get; set; }

    public virtual ICollection<DrillLog> DrillLogs { get; set; } = new List<DrillLog>();

    public virtual ICollection<DrillPattern> DrillPatterns { get; set; } = new List<DrillPattern>();

    public virtual ICollection<Drilling> Drillings { get; set; } = new List<Drilling>();

    public virtual ICollection<Employee> InverseSupervisorSsnNavigation { get; set; } = new List<Employee>();

    public virtual EmployeeRole? JobTitleNavigation { get; set; }

    public virtual Employee? SupervisorSsnNavigation { get; set; }
}