// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WebApp.Entities;

public partial class Quarry
{
    public string Name { get; set; } = null!;

    public string Location { get; set; } = null!;

    public string Company { get; set; } = null!;

    public string? RockType { get; set; }

    public int? AnnualProduction { get; set; }

    public virtual ICollection<DrillLog> DrillLogs { get; set; } = new List<DrillLog>();
}